# Generated by Django 5.0.6 on 2024-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2022-01-15'),
            preserve_default=False,
        ),
    ]
